services:
  - type: web
    name: snake-game
    env: python
    region: singapore
    plan: free
    pythonVersion: 3.11
    startCommand: "streamlit run streamlit_snake_game.py --server.port=8080"
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_PORT
        value: "8080"
